// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUOkaMpd2TuII1rl6Xklem7dW-uJ3K44A',
    appId: '1:401955570059:web:9d8056f139d7f827a8ef8e',
    messagingSenderId: '401955570059',
    projectId: 'jokesapp-52ad9',
    authDomain: 'jokesapp-52ad9.firebaseapp.com',
    storageBucket: 'jokesapp-52ad9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCd1qbek9V8xVQZmjGagV-kWMd7Qdwmrec',
    appId: '1:401955570059:android:f3b098ab8fd15d21a8ef8e',
    messagingSenderId: '401955570059',
    projectId: 'jokesapp-52ad9',
    storageBucket: 'jokesapp-52ad9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDveUedQdNbyRKPSkbt1jgpzGYEQiLo4os',
    appId: '1:401955570059:ios:0c53704771406ba0a8ef8e',
    messagingSenderId: '401955570059',
    projectId: 'jokesapp-52ad9',
    storageBucket: 'jokesapp-52ad9.firebasestorage.app',
    iosBundleId: 'com.example.jokesapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDveUedQdNbyRKPSkbt1jgpzGYEQiLo4os',
    appId: '1:401955570059:ios:0c53704771406ba0a8ef8e',
    messagingSenderId: '401955570059',
    projectId: 'jokesapp-52ad9',
    storageBucket: 'jokesapp-52ad9.firebasestorage.app',
    iosBundleId: 'com.example.jokesapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUOkaMpd2TuII1rl6Xklem7dW-uJ3K44A',
    appId: '1:401955570059:web:0ec55236dced2c64a8ef8e',
    messagingSenderId: '401955570059',
    projectId: 'jokesapp-52ad9',
    authDomain: 'jokesapp-52ad9.firebaseapp.com',
    storageBucket: 'jokesapp-52ad9.firebasestorage.app',
  );
}
